processing/load_body.py, setup.py, tests/test_load_body.py
@fabiobatalha 
por gentileza poderia aplicar esse ajuste e rodar o load_body.py somente para o ISSN: 1135-5727 (Revista Espanhola de Saúde Pública)
=> Normalizando o unicode coletado pelo scraping.

development.ini-TEMPLATE, production.ini-TEMPLATE
Os ajustem atualizam o valor padrão da diretiva `mongo_uri`, que deixou
de aceitar valores no formato DSN e passou a aceitar `<maquina>:<porta>`,
e removem as configurações relativas a integração com Sentry no ambiente
de desenvolvimento, que não faz sentido.
=> Ajusta gabaritos dos arquivos de configuração.

articlemeta/controller.py
Nessa primeira parte:
1. Os métodos no estilo ``DataBroker.get_articles`` e ``DataBroker.get_issues`` deram origem a ``ArticleMeta.get`` e ``IssueMeta.get``;
2. Os nomes das bases de dados e coleções do MongoDB foram desacopladas dos métodos;
3. As dependências de dados de outras coleções do MongoDB foram explicitadas; Por exemplo: `IssueMeta` depende de `JournalMeta`.
=> Parte 1 da refatoração do módulo controller.py.

processing/load_languages.py, tests/test_load_languages.py
Padrões possíveis:
- xml: delta/v32n2/1678-460X-delta-32-02-00543.xml
- html: V:\\Scielo\\serial\\dpjo\\v15n3\\markup\\05.htm
- pdf: d:/c.917173/scielo/serial.lilacs//mioc/v51/markup/v51/tomo51(f1)_17-74.pdf
Fixes #145
=> Considerar .pdf como mais um dos padrões de arquivo fonte, além de xml e html

articlemeta/export.py
Faz com que o "fulltexts" volte a ser retornado
articlemeta/export.py
```
from articlemeta.client import ThriftClient
cl = ThriftClient()
article = cl.document(code='S0074-02761929000100003', collection='scl', fmt='opac')
article.data['fulltexts']
```
Retorno esperado:
```json
{"pdf": 
{"fr": "http://www.scielo.br/pdf/mioc/v22n1/fr_tomo22(f1)_135-139.pdf",
"pt": "http://www.scielo.br/pdf/mioc/v22n1/tomo22(f1)_135-139.pdf"},
"html": 
{"pt": "http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0074-02761929000100003&tlng=pt"}}
```
"fulltexts" foi erroneamente removido ao solucionar #116.
Fixes #149
n/a
n/a
tk149
=> O fmt=opac deve retornar "fulltexts"

articlemeta/export.py, setup.py
Faz com que o "fulltexts" volte a ser retornado
articlemeta/export.py
```
from articlemeta.client import ThriftClient
cl = ThriftClient()
article = cl.document(code='S0074-02761929000100003', collection='scl', fmt='opac')
article.data['fulltexts']
```
Retorno esperado:
```json
{"pdf": 
{"fr": "http://www.scielo.br/pdf/mioc/v22n1/fr_tomo22(f1)_135-139.pdf",
"pt": "http://www.scielo.br/pdf/mioc/v22n1/tomo22(f1)_135-139.pdf"},
"html": 
{"pt": "http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0074-02761929000100003&tlng=pt"}}
```
"fulltexts" foi erroneamente removido ao solucionar #116.
Fixes #149
n/a
n/a
tk149
master_tk149
=> O fmt=opac deve retornar "fulttexts"

articlemeta/data/collections.json, articlemeta/thrift/articlemeta.thrift, articlemeta/thrift/server.py, setup.py
Corrigir o erro na consulta de Identifiers de Collections no Thrift Server, onde há campos obrigatórios e opcionais de collection, que estão sendo encarados como obrigatórios. Os detalhes do problema estão na issue #155. 
Em `articlemeta/thrift/server.py`, no método `get_collection_identifiers()`, e em `articlemeta/data/collections.json` com os campos obrigatórios para Collection.
Utilizar o script `articlemeta/thrift/client_sample.py`, alterando as configurações do AM, e executar:
`client.get_collection_identifiers()`
`client.get_collection(code='scl')`
O seguinte dado nos identifiers de coleções está retornando do AM e causando o erro no Thrift Server:
```
{
'domain': 'books.scielo.org',
'has_analytics': False,
'is_active': True,
'name': {'en': 'SciELO Books', 'es': 'SciELO Libros', …
```
=> Corrigidos dados de SciELO Books e retorno de get_collection_identifiers

articlemeta/thrift/server.py, setup.py
- Em `thrift.server.Dispacher.get_collection()`, lança exceção caso o retorno de `DataBroker.get_collection()` seja None. Também trata os parâmetros opcionais desse retorno.
- Adiciona logs de debug na entrada de todos os métodos
=> Trata retorno no get_collection do Thrift e adiciona logs debug

articlemeta/articlemeta.py, articlemeta/export.py, articlemeta/export_crossref.py, requirements.txt, setup.py, tests/test_export_crossref.py
No XML do CrossRef incluir um DOI para cada versão de idioma do documento, se fornecido no XML do SPS, ou seja, se estiver registrado na base ISIS, no campo v337, e acessível pelo xylose como  ``Article.doi_and_lang``.
1. Onde havia apenas 1 ``journal_article`` por documento fica 1 ``journal_article`` para cada DOI / idioma disponível.
2. Dentro do elemento ``journal_article/titles``, incluir o elemento ``original_language_title``, além do ``title``.
Exemplo:
```xml
<titles>
<title>TÍTULO DO ARTIGO (VERSÃO TRADUÇÃO)</title>
<original_language_title language="en">An article in its original language which happens to be English</original_language_title>
</titles>
```
3. Incluir um novo elemento ``related_item``:
```xml
<program xmlns="http://www.crossref.org/relations.xsd">
<related_item> …
```
=> [DOIMultilingue] Incluir no XML do CrossRef um DOI para cada versão (idioma) de documento

setup.py, tests/test_export_crossref.py
Corrige testes que usam **Article.publication_date** do **xylose**. Como houve correção neste atributo, o resultado é diferente do esperado e os testes quebraram no articles_meta, ao gerar XML do CrossRef.
-  tests/test_export_crossref.py
``python setup.py test -s tests/test_export_crossref.py``
Escrevi um email para o contato do CrossRef pedindo orientação a respeito de como enviaremos a data, já que há caso que temos a data do artigo e a data do fascículo. Devemos enviar as duas? ou somente a do fascículo? Por não saber ainda esta resposta, apenas corrigi os testes. Após ter a orientação do CrossRef, devemos verificar se **XMLArticlePubDatePipe.transform()** atende.
N/A
N/A
https://github.com/scieloorg/xylose/pull/176
=> Corrige testes após atualizacao de xylose para 1.35.4

articlemeta/export.py, articlemeta/export_crossref.py, tests/test_export_crossref.py
Este pull request adiciona a possibilidade de exportar o XML-CrossRef com as licenças de uso pertinentes ao artigo exportado (se houver).
- `articlemeta/export_crossref.py` L: `561`
Para testar manualmente este PR deve-se:
- Iniciar o ArticleMeta;
- Fazer uma requisição para um artigo que possua licença de uso;
- Observar a adição da licença referida pelo artigo;
- Fazer uma requisição para um artigo que não possua licença de uso;
- Observar a não adição de licença para o artigo;
N/A
N/A
#165 
[Access Indicator XSD](https://data.crossref.org/reports/help/schema_doc/doi_resources4.3.6/AccessIndicators_xsd.html)
[CrossRef Schema DOC](http://data.crossref.org/reports/help/schema_doc/4.4.0/fundref_xsd.html#program)
[CrossRef XSL](https://github.com/CrossRef/jats-crossref-xslt/blob/12eb020e4d9b …
=> Adiciona licença de uso ao exportar para o CrossRef

requirements.txt, setup.py
Atualizar a versão do xylose para 1.35.5, que corrige os valores dos subcampos de idioma e DOI no campo v337.
n/a
n/a
n/a
n/a
https://github.com/scieloorg/xylose/issues/177
n/a
=> Altera a versão do xylose para 1.35.5

articlemeta/export_rsps.py, tests/test_export_rsps.py
Adiciona o PID SciELO V1 no XML formato SPS, primeira versão do SciELO PID, presente nos primeiros artigos publicados.
Em `articlemeta/export_rsps.py`, no pipe que trata dos *Publisher IDs*
- Acesse um artigo informando no path o atributo `format=xmlrsps` para retornar o XML sintetizado
- Verifique se está presente o campo [v2] do artigo na tag, como no exemplo:
```xml
<article-id pub-id-type="publisher-id" specific-use="scielo-v1">S2176-4573(12)00700101</article-id>
```
N/A
N/A
#193, scieloorg/document-store-migracao/issues/215
ADR sobre novo PID: https://github.com/scieloorg/kernel/blob/master/docs/adr/0006-novo-pid-do-scielo.md
=> Adiciona o PID scielo-v1 no XML SPS

articlemeta/utils.py, tests/test_utils.py
Este pull request corrige um comportamento não esperado durante a transformação das tags `<a>` dentro do elemento `mixed-citation` do `artigo` no formato `xmlrsps`. 
- `articlemeta/utils.py` L: `17`
Para testar este pr manualmente deve-se:
- Iniciar uma instância do article meta:
- Acessar o artigo via url `/api/v1/article/?collection=scl&code=S0021-75572002000300005&format=xmlrsps`;
- Verificar que as tags `a` sem `href` não foram transformadas em `ext-link`.
N/A
#188 
N/A
=> Ignora a transformação de links inválidos no elemento mixed-citation

articlemeta/export_rsps.py, tests/test_export_rsps.py
Este pull request corrige a produção de XML para o formato `xmlrsps` onde o `<volume>` e `<issue>` são capturados a partir da propriedade `.issue` ou do próprio `artigo`.
- `articlemeta/export_rsps.py` L: `980`
Para testar este pull request manualmente, deve-se:
- Rode uma instância do Article Meta;
- Acesse um artigo objeto do problema (ex `api/v1/article/?collection=cub&code=S0253-570X2018000100010&format=xmlrsps`);
- Observe que as tags `volume` e `issue` foram preenchidas;
- Acesse um `artigo` publicado em um`suplemento` (ex `/api/v1/article/?collection=scl&format=xmlrsps&code=S0034-89102018000200506`)
- Observe que o suplemento foi preenchido adequadamente;
- Acesse um documento do tipo `ahead`;
- Observe que as tags de `volume` e `issue` não foram preenchidos;
Optei por manter a …
=> Adiciona fallback para `issue` e `volume` durante pipeline do xmlrsps

processing/load_doi.py, processing/load_licenses.py
Resolve exceção do tipo `TypeError` que causa a interrupção da execução dos utilitários `articlemeta_loadlicense` e `articlemeta_loaddoi`.
A modificação é extremamente pequena, portanto não há como dar uma dica aqui.
Execute os comandos `articlemeta_loadlicense -h` e `articlemeta_loaddoi -h` e observe que não é levantada nenhuma exceção.
obs: a execução dos comandos necessita de uma instância de MongoDB, mesmo que nenhuma ação seja de fato executada.
n/a
n/a
#198 
n/a
=> Corrige TypeError na execução dos utilitários *articlemeta_loadlicense* e *articlemeta_loaddoi*

articlemeta/export_rsps.py, requirements.txt, setup.py, tests/test_export_rsps.py
Este PR corrige a exportação de XMLs SPS, especificamente no campo `email` das afiliações.
Em `tests/test_export_rsps.py`, que possui teste que exemplifica como o dado está na base ISIS.
Executando `python setup.py test -s tests.tex_export_rsps`
OU
Acesse algum artigo via API REST com `format=xmlrsps` que tenha campo email na afiliação, com e sem a tag HTML `<a>`. Nos dois casos, o email deve retornar somente com o texto da tag. Exemplo de artigo com tag HTML no campo: `http://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0102-311X2007000100001&format=xmlrsps`.
Alguns artigos HTML tiveram o campo de email da afiliação marcado com a tag `<a>`. Esta alteração utiliza campo tratado no Xylose para resolver o problema na exportação do XML SPS caso exista.
#185
Nenhuma.
=> Corrige campo email da afiliação na exportação do XML SPS

processing/load_licenses.py
Corrige execução incorreta da função `processing.load_licenses.collection_info`.
A mudança é mínima, vá ao visualizador de códigos do próprio GitHub.
Será necessário executar o comando em uma instância local, por exemplo `articlemeta_loadlicenses -c cub`.
n/a
n/a
#203 
n/a
=> Corrige argumentos passados para função collection_info

articlemeta/export.py, articlemeta/export_rsps.py, tests/test_export_rsps.py
Este pull request adiciona ao formato `rsps` a tag `self-uri` quando o artigo exportado tiver `pdfs` associados ao seu registro.
- `articlemeta/export_rsps.py`: L: `1165`
Para testar este PR manualmente, deve-se:
- Executar uma instância do article meta;
- Acessar um artigo (ex `S0074-02761922000100006`) utilizando o formato `xmlrsps`;
- Observar a tag `self-uri` referenciando o(s) pdf(s) do artigo;
- Acessar um artigo que não possui `pdf`;
- Observar que a tag `self-uri` não é renderizada.
N/A
https://github.com/scieloorg/document-store-migracao/issues/206
N/A
=> Adiciona tag self-uri para a exportação de XML no formato rsps

articlemeta/export_sci.py, tests/test_export_sci.py
O documento http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1516-35982019000100604&tlng=en
possui um referência bibliográfica com DOI https://doi.org/10.1671/0272-4634(2007)27[247:AESITS]2.0.CO;2.
Ao acessar este documento no articlemeta utilizando o formato `xmlwos` o XML
resultante é inválido em relação ao schema do web of science. A mensagem de
erro é a seguinte:
`Element 'ext-link', attribute 'href': 'https://doi.org/10.1671/0272-4634(2007)27[247:AESITS]2.0.CO;2'
is not a valid value of the atomic type 'xs:anyURI'., line 329`
Com esta mudança o *path* da URL do DOI passa a ser codificada, trocando
caracteres inválidos por suas sequências de escape correspondentes.
n/a
Na sua instância local do articlemeta acesse `/api/v1/article/?collection=scl&code=S1516-35982019000100604&form …
=> Corrige URL inválida no XML do SciELO CI

articlemeta/export_rsps.py
Corrige o erro
```
04/02/2020 10:45:52  File "/usr/local/lib/python3.5/site-packages/articlemeta/export_rsps.py", line 475, in transform
04/02/2020 10:45:52    frontstub.append(abstract)
04/02/2020 10:45:52UnboundLocalError: local variable 'abstract' referenced before assignment
```
por commits
Instanciando o Article com um json que contém abstracts de tradução, mas não tem o abstract no idioma correspondente ao idioma do sub-article. No caso deste documento, o erro também era no dado.
n/a
n/a
#206 
n/a
=> Corrige o código para resolver:  local variable 'abstract' referenced before assignment

articlemeta/export_rsps.py, articlemeta/export_sci.py, tests/test_export_rsps.py, tests/test_export_sci.py
Este pull request altera o método utilizado para recupera a data das citações nos formatos `xmlwos` e `xmlrsps`.
- `articlemeta/export_rsps.py` L: `213`
- `articlemeta/export_sci.py` L: `231`
Para testar este pull request manualmente, deve-se:
- Acesse as páginas:
- [formato xml rsps](http://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0001-37652008000100006&format=xmlrsps)
- [formato xml wos](http://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0001-37652008000100006&format=xmlwos)
- Verifique se as datas da referência `B25` estão de acordo com o requerido (apenas o ano).
N/A
N/A
closes #187 
N/A
=> Corrige a data de publicação para as citações nos formatos xmlwos e xmlrsps

articlemeta/export_crossref.py, tests/test_export_crossref.py
Este pull request corrigue a data de publicação para as citações quando o artigo é exportado no formato `xmlcrossref`.
- `articlemeta/export_crossref.py`
Para testar este pull request manualmente, deve-se:
- Acesse a URL `api/v1/article/?collection=scl&code=S0001-37652008000100006&format=xmlcrossref`;
- Verifique a referência `25`;
- Observe que o ano de publicação em `cYear` é `1985`;
N/A
N/A
closes #187 
N/A
=>  Corrige a data de publicação para as citações no formato xmlcrossref

articlemeta/export_rsps.py, tests/test_export_rsps.py
Adiciona o atributo `fpage/@seq` no _front_ do formato _xmlrsps_ quando este valor estiver disponível.
O valor do atributo `@seq` é importante para desambiguar documentos que
iniciam numa mesma página de um mesmo fascículo.
n/a
Após aplicar o _patch_, teste com o documento `/api/v1/article/?body=false&collection=scl&code=S0001-37652000000400034&format=xmlrsps`, conforme descrito no ticket #213.
n/a
n/a
#213 
n/a
=> Adiciona fpage/@seq ao formato xmlrsps

processing/load_mixedcitations.py, requirements.txt, setup.py
Este pull request melhora a combinação dos títulos durante a fase de auditoria, porque algumas citações deixavam de ser carregadas por ter tags entre palavras ou espaços em demasia. Escapa a "tag" <http presente em alguns artigos de forma errônea. Também modifica o namespace `w` para que seja possível ter uma citação válida.
- `processing/load_mixedcitations.py`
Para testar este pull requests manualmente, deve-se:
- Baixe as citações [1];
- Faça a carga em uma instância do *AM*.
- Verifique que as citações foram carregadas com sucesso e que as tags foram escapadas de maneira adequada.
Alguns artigos não poderão ser exibidos em sua plenitude porque dependem de um outro pull request para corrigir o [xylose](https://github.com/scieloorg/xylose/pull/190).
N/A
#217
[[1] - mixed citations dos …
=> Corrige a carga das mixed citations

processing/__init__.py, processing/load_body.py, tests/test_load_languages.py, tests/test_utils.py
Este pull request aplica uma função para escapar as falsas tags `<http>` durante a carga dos HTMLs pelo A.M. O processo consiste em alterar a string capturada durante a requisição HTTP, substituindo `<http>` por `&lt;http&gt;`.
- Pelo commit `e9986ef`
- Baixe o arquivo [S0104-87752008000100005.txt](https://github.com/scieloorg/articles_meta/files/5960789/S0104-87752008000100005.txt);
- Carregue-o no seu mongodb com o comando `mongoimport --db articlemeta --collection articles --file S0104-87752008000100005.txt`
- Execute o comando `python processing/load_body.py --logging_level DEBUG -p S0104-87752008000100005 -c sc`
- Acesse o artigo no seu [A.M](http://localhost:8000/api/v1/article/?collection=scl&code=S0104-87752008000100005&format=xylose&body=true);
- Verifique que os locais onde …
=> Corrige a carga do HTML quando falsas tags <http> são encontradas

articlemeta/export.py, articlemeta/export_crossref.py, tests/test_export_crossref.py
Fix absence of elements to identify has translation and is translation of
por commits
Executei os comandos a seguir no ipython
```python
doc = requests.get(
"https://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0034-75902021000300300"
)
import json
data = json.loads(doc.text)
from articlemeta import export_crossref
from articlemeta.export import CustomArticle
xylose_article = CustomArticle(data)
import plumber
ppl = plumber.Pipeline(
export_crossref.SetupDoiBatchPipe(),
export_crossref.XMLHeadPipe(),
export_crossref.XMLBodyPipe(),
export_crossref.XMLDoiBatchIDPipe(),
export_crossref.XMLTimeStampPipe(),
export_crossref.XMLDepositorPipe(),
export_crossref.XMLRegistrantPipe(),
export_crossref.XMLJournalPipe(),
export_crossref.XMLJournalMetadataPipe(), …
```
=> Fix the absence of elements to identify has translation and is translation of

articlemeta/export_crossref.py, setup.py, tests/test_export_crossref.py
Completa os metadados multilingues do artigo (`journal_article`) com um título alternativo.
Recomendação feita pelo CrossRef (http://support.crossref.org/hc/requests/407513), ao solicitar orientações sobre como complementar os dados multilingues dos artigos. No caso, somente faltavam os títulos.
[S0034-75902021000300300_crossref_IF_updated.xml.zip](https://github.com/scieloorg/articles_meta/files/8393042/S0034-75902021000300300_crossref_IF_updated.xml.zip)
por commits
```python
doc = requests.get(
"https://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0034-75902021000300300"
)
import json
data = json.loads(doc.text)
from articlemeta import export_crossref
from articlemeta.export import CustomArticle
xylose_article = CustomArticle(data)
import plumber
ppl = …
```
=> Completa os metadados multilingues do artigo com um título alternativo (`original_language_title`)

articlemeta/export_crossref.py, tests/test_export_crossref.py
Remove a dependência da existência do dado `document["fulltexts"]["pdfs"]` gerado a partir do processamento `load_languages`
No lugar do path dos pdfs, coloca o link da página do pdf: `http://www.scielo.br?script=sci_arttext&pid=<pid>&tlng=<lang>`
por commits
Execute no ipython
```python
doc = requests.get(
"https://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S0034-75902021000300300"
)
import json
data = json.loads(doc.text)
from articlemeta import export_crossref
from articlemeta.export import CustomArticle
xylose_article = CustomArticle(data)
import plumber
ppl = plumber.Pipeline(
export_crossref.SetupDoiBatchPipe(),
export_crossref.XMLHeadPipe(),
export_crossref.XMLBodyPipe(),
export_crossref.XMLDoiBatchIDPipe(),
export_crossref.XMLTimeStampPipe(), …
```
=> Preenche o campo resource com o link para a versão do pdf correspondente

Dockerfile-dev, requirements.txt
Corrige Dockerfile-dev e dependência WebOb para o ambiente de desenvolvimento
pelos commits
1. docker build -f Dockerfile-dev -t article_meta_dev:latest .
2. docker run --name my-articlemeta -d article_meta_dev
Para desenvolvimento e testes do build do projeto, é possível simular uma conexão com o MongoDB da seguinte forma:
Originalmente, no arquivo controller.py,  a conexão com o MongoDB é feita assim:
```python
db_url = urlparse(db_dsn)
conn = pymongo.MongoClient('mongodb://%s' % db_url.netloc)
db = conn[db_url.path[1:]]
_create_indexes(db)
return db
```
Para simular (fakear) a conexão com o MongoDB, você pode usar a biblioteca mongomock desta maneira:
```python
db_url = urlparse(db_dsn)
import mongomock
conn = mongomock.MongoClient('mongodb://localhost')
db = conn[db_url.path[1:]] …
```
=> Corrige Dockerfile-dev e dependência WebOb para o ambiente de desenvolvimento

articlemeta/export_sci.py
Adiciona o ``orcid`` no contrib group para o formato xmlwos.
Por commit.
Acessando a URL:http://localhost:8000/api/v1/article/?code=S1808-24322023000100234&format=xmlrsps
N/A
Não há tíquete para essa atividade.
N/A
=> Adiciona o ``orcid`` no contrib group para o formato xmlwos.

articlemeta/export_sci.py
Adiciona tratamento de erro para URL em formato não esperado.
Sugiro verificar o módulo **export_sci.py**
Para teste sugiro acessa o link: http://0.0.0.0:8000/api/v1/article/?collection=cub&code=S1024-94352003000500002&format=xmlwos
N/A
https://github.com/scieloorg/articles_meta/issues/277
N/A
=> Adiciona tratamento de erro para URL em formato não esperado.

articlemeta/export_crossref.py
Verifica a existência de resumo traduzido na classe XMLArticleAbstracttPipe;
pelos commits
```python
import json
from articlemeta.export_crossref import XMLArticleAbstractPipe
from articlemeta.export import CustomArticle as Article
from tests.test_export_crossref import create_xmlcrossref_with_n_journal_article_element
response = requests.get("https://articlemeta.scielo.org/api/v1/article/?code=S2175-91462024000100401")
content  = json.loads(response.content)
article = Article(content)
xmlcrossref = create_xmlcrossref_with_n_journal_article_element(['en'])
data = [article, xmlcrossref]
raw, xml = XMLArticleAbstractPipe().transform(data)
from lxml import etree as ET
ET.tostring(xml)
```
N/A
N/A
#283 
N/A
=> Verifica a existência de resumo traduzido na classe XMLArticleAbstracttPipe;

articlemeta/export_crossref.py
fix: corrige extração de nomes de patrocinadores no método `append_funding_data`
pelos commits
ipython
```python
import json
from articlemeta.export_crossref import XMLFundingDataPipe
from articlemeta.export import CustomArticle as Article
from tests.test_export_crossref import create_xmlcrossref_with_n_journal_article_element
response = requests.get("https://articlemeta.scielo.org/api/v1/article/?code=S0102-86502024000100201")
content  = json.loads(response.content)
article = Article(content)
xmlcrossref = create_xmlcrossref_with_n_journal_article_element(['pt', 'en', 'es'])
data = [article, xmlcrossref]
raw, xml = XMLFundingDataPipe().transform(data)
from lxml import etree as ET
ET.tostring(xml)
```
N/A
N/A
#286 
N/A
=> fix: corrige extração de nomes de patrocinadores no método `append_funding_data`

articlemeta/export_crossref.py, requirements.txt, tests/test_export_crossref.py
Realiza correções em XMLFundingDataPipe.transform
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique um contexto onde as modificações se fazem necessárias ou passe informações que contextualizam
o revisor a fim de facilitar o entendimento da funcionalidade.
Quando aplicável e se fizer possível adicione screenshots que remetem a situação gráfica do problema que o pull request resolve.
Indique uma issue ao qual o pull request faz relacionamento.
Indique as referências utilizadas para a elaboração do pull request.
=> Fix: XMLFundingDataPipe.transform

articlemeta/export_crossref.py
Fix XMLFundingDataPipe.precond
pelos commits
```python
python3 -m unittest tests.test_export_crossref.ExportCrossRef_XMLFundingData_Tests
```
N/A
N/A
N/A
N/A
=> Fix XMLFundingDataPipe.precond

articlemeta/export_sci.py
- Altera ordem do elemento 'month' na classe DataPipe.
- Altera XMLArticleMetaContribGroupPipe para criar elemento apenas se o valor de "role" igual 'ND' ou 'ED'
pelos commits
executar o teste:
```python python -m unittest article_meta.tests.test_xml_citation_date_with_year_and_month_and_day_pipe```
```python python -m unittest article_meta.tests.test_xmlarticle_meta_contrib_group_author_names_pipe```
N/A
N/A
#294
#292 
N/A
=> Altera ordem dos elementos de Data e classe XMLArticleMeta

articlemeta/export_sci.py, tests/test_export_sci.py
Adiciona validação e extração de URLs válidas em URIPipe.
pelos commits
```python python3 -m unittest article_meta.tests.XMLCitationTests.test_xml_citation_with_broken_url_pipe```
N/A
N/A
#293 
N/A
=> Adiciona validação e extração de URLs válidas em URIPipe
